// <auto-generated />
using System;
using ApiChamados.Adapters.Data.dbContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ApiChamados.Adapters.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ApiChamados.Adapters.Data.Entities.AnexoDbModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NomeArquivo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ReclamacaoId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ReclamacaoId");

                    b.ToTable("Anexos");
                });

            modelBuilder.Entity("ApiChamados.Adapters.Data.Entities.ClienteDbModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("ApiChamados.Adapters.Data.Entities.ReclamacaoCategoriaDbModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ReclamacaoId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ReclamacaoId");

                    b.ToTable("Categorias");
                });

            modelBuilder.Entity("ApiChamados.Adapters.Data.Entities.ReclamacaoDbModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ClienteId")
                        .HasColumnType("uuid");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("DataRecebimento")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("SLAViolado")
                        .HasColumnType("boolean");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Texto")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UltimaNotificacaoSLA")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.ToTable("Reclamacoes");
                });

            modelBuilder.Entity("ApiChamados.Adapters.Data.Entities.AnexoDbModel", b =>
                {
                    b.HasOne("ApiChamados.Adapters.Data.Entities.ReclamacaoDbModel", "Reclamacao")
                        .WithMany("Anexos")
                        .HasForeignKey("ReclamacaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Reclamacao");
                });

            modelBuilder.Entity("ApiChamados.Adapters.Data.Entities.ReclamacaoCategoriaDbModel", b =>
                {
                    b.HasOne("ApiChamados.Adapters.Data.Entities.ReclamacaoDbModel", "Reclamacao")
                        .WithMany("Categorias")
                        .HasForeignKey("ReclamacaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Reclamacao");
                });

            modelBuilder.Entity("ApiChamados.Adapters.Data.Entities.ReclamacaoDbModel", b =>
                {
                    b.HasOne("ApiChamados.Adapters.Data.Entities.ClienteDbModel", "Cliente")
                        .WithMany("Reclamacoes")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("ApiChamados.Adapters.Data.Entities.PerfilClienteDbModel", "PerfilCliente", b1 =>
                        {
                            b1.Property<Guid>("ReclamacaoDbModelId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Cpf")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.PrimitiveCollection<string>("Produtos")
                                .IsRequired()
                                .HasColumnType("jsonb");

                            b1.Property<int>("RelacionamentoAnos")
                                .HasColumnType("integer");

                            b1.Property<string>("Risco")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<int>("ScoreCredito")
                                .HasColumnType("integer");

                            b1.HasKey("ReclamacaoDbModelId");

                            b1.ToTable("Reclamacoes");

                            b1.WithOwner()
                                .HasForeignKey("ReclamacaoDbModelId");
                        });

                    b.Navigation("Cliente");

                    b.Navigation("PerfilCliente")
                        .IsRequired();
                });

            modelBuilder.Entity("ApiChamados.Adapters.Data.Entities.ClienteDbModel", b =>
                {
                    b.Navigation("Reclamacoes");
                });

            modelBuilder.Entity("ApiChamados.Adapters.Data.Entities.ReclamacaoDbModel", b =>
                {
                    b.Navigation("Anexos");

                    b.Navigation("Categorias");
                });
#pragma warning restore 612, 618
        }
    }
}
